In [1]:
import numpy as np
a = np.array([1,2,3,4]) 
print(a)
print(a.shape) # matrix

[1 2 3 4]


In [5]:
import numpy as np
b = np.array([[1,2,3], [4,5,6]]) 
print(b)
print(b.shape) # matrix

[[1 2 3]
 [4 5 6]]
(2, 3)


In [6]:
import numpy as np
a = np.array([1,2,3]) 
b = np.array([4,5,6]) 
print(a + b) 
print(a * b) 
print(a.mean())

[5 7 9]
[ 4 10 18]
2.0


In [7]:
import numpy as np
import time

python_list = list(range(1000000))
numpy_array = np.arange(1000000)

start = time.time()
sum(python_list)
print("Python list:", time.time() - start)

start = time.time()
numpy_array.sum()
print("NumPy array:", time.time() - start)

Python list: 0.010344982147216797
NumPy array: 0.0007112026214599609


In [10]:
arr = np.array([5,10,15,20]) 
print(arr.mean())

12.5


In [9]:
m = np.array([[1,2],[3,4]]) 
print(m.shape)

(2, 2)


In [12]:
a = np.array([2,4,6]) 
b = np.array([1,3,5]) 
print(a*b)

[ 2 12 30]
